### ISSUE TITLE
ImportError: No module named sqlalchemy_utils.types.choice after success installation with pip.

### ISSUE THREAD

**Issue by nmb10** [franc3000/datastore#13]
[20:05:38] Franklin Sarkett: $ datastore-alembic.py revision --autogenerate -m 'New column Target.target_potential'
Traceback (most recent call last):
  File "/Users/franklin/venv/bin/datastore-alembic.py", line 6, in <module>
    exec(compile(open(__file__).read(), file, 'exec'))
  File "/Users/franklin/Documents/Code/datastore/bin/datastore-alembic.py", line 18, in <module>
    main(argv=alembic_argv)
  File "/Users/franklin/venv/lib/python2.7/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/franklin/venv/lib/python2.7/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/Users/franklin/venv/lib/python2.7/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/Users/franklin/venv/lib/python2.7/site-packages/alembic/command.py", line 117, in revision
    script_directory.run_env()
  File "/Users/franklin/venv/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/Users/franklin/venv/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/franklin/venv/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/Users/franklin/Documents/Code/datastore/datastore/migrations/env.py", line 7, in <module>
    from datastore.models import Base
  File "/Users/franklin/Documents/Code/datastore/datastore/models/__init__.py", line 6, in <module>
    from .individual import IndividualFactory
  File "/Users/franklin/Documents/Code/datastore/datastore/models/individual.py", line 6, in <module>
    from sqlalchemy_utils.types.choice import ChoiceType
ImportError: No module named sqlalchemy_utils.types.choice

**Comment by nmb10** [comment]
Done. Requires v0.1.4.
