### ISSUE TITLE
Unable to install because of IOError: [Errno 2] No such file or directory: 'README.rst'

### ISSUE THREAD

**Issue by nmb10** [franc3000/datastore#16]
```bash
pip install ../path/to/datastore --upgrade
```
Processing /home/nmb10/projects/frank/datastore
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-rlnlRp-build/setup.py", line 8, in <module>
        with open('README.rst') as readme_file:
    IOError: [Errno 2] No such file or directory: 'README.rst'

**Comment by nmb10** [comment]
Done.
