### ISSUE TITLE
ImportError: No module named consumer_view

### ISSUE THREAD

**Issue by nmb10** [franc3000/datastore#17]
```bash
$ datastore-alembic.py upgrade head
```
```
Traceback (most recent call last):
  File "/home/nmb10/.virtualenvs/bartok/bin/datastore-alembic.py", line 18, in <module>
    main(argv=alembic_argv)
  File "/home/nmb10/.virtualenvs/bartok/local/lib/python2.7/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/nmb10/.virtualenvs/bartok/local/lib/python2.7/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/home/nmb10/.virtualenvs/bartok/local/lib/python2.7/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/home/nmb10/.virtualenvs/bartok/local/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/home/nmb10/.virtualenvs/bartok/local/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/nmb10/.virtualenvs/bartok/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/nmb10/.virtualenvs/bartok/local/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/home/nmb10/.virtualenvs/bartok/local/lib/python2.7/site-packages/datastore/migrations/env.py", line 7, in <module>
    from datastore.models import Base
  File "/home/nmb10/.virtualenvs/bartok/local/lib/python2.7/site-packages/datastore/models/__init__.py", line 4, in <module>
    from .consumer_view import ConsumerViewFactory
ImportError: No module named consumer_view
```

**Comment by nmb10** [comment]
Done.
